import {
  ApolloIcon,
  AsanaIcon,
  AwsIcon,
  BootstrapIcon,
  ExpressIcon,
  FramerMotionIcon,
  GithubIcon,
  GitIcon,
  GraphQlIcon,
  IyzicoIcon,
  JavaScriptIcon,
  JiraIcon,
  MaterialUiIcon,
  MongoIcon,
  NextIcon,
  NodeIcon,
  PaypalIcon,
  PostgreIcon,
  ReactIcon,
  ReactQueryIcon,
  ReduxIcon,
  SassIcon,
  ShadcnIcon,
  SlackIcon,
  StripeIcon,
  SwrIcon,
  TailwindIcon,
  TypeScriptIcon,
} from "@/components/Icons";

export const ALL_TECHS = [
  {
    name: "Next",
    icon: NextIcon,
    categories: ["frontend"],
  },
  {
    name: "React",
    icon: ReactIcon,
    categories: ["frontend"],
  },
  {
    name: "Redux",
    icon: ReduxIcon,
    categories: ["frontend"],
  },
  {
    name: "TypeScript",
    icon: TypeScriptIcon,
    categories: ["frontend", "backend"],
  },
  {
    name: "JavaScript",
    icon: JavaScriptIcon,
    categories: ["frontend", "backend"],
  },
  {
    name: "Express",
    icon: ExpressIcon,
    categories: ["backend"],
  },
  {
    name: "Apollo",
    icon: ApolloIcon,
    categories: ["frontend", "backend"],
  },
  {
    name: "AWS",
    icon: AwsIcon,
    categories: ["backend"],
  },
  {
    name: "MongoDB",
    icon: MongoIcon,
    categories: ["backend"],
  },
  {
    name: "PostgreSQL",
    icon: PostgreIcon,
    categories: ["backend"],
  },
  {
    name: "Node",
    icon: NodeIcon,
    categories: ["backend"],
  },
  {
    name: "SWR",
    icon: SwrIcon,
    categories: ["frontend"],
  },
  {
    name: "ReactQuery",
    icon: ReactQueryIcon,
    categories: ["frontend"],
  },
  {
    name: "GraphQL",
    icon: GraphQlIcon,
    categories: ["frontend"],
  },
  {
    name: "Git",
    icon: GitIcon,
    categories: ["other"],
  },
  {
    name: "GitHub",
    icon: GithubIcon,
    categories: ["other"],
  },
  {
    name: "Framer",
    icon: FramerMotionIcon,
    categories: ["frontend"],
  },
  {
    name: "Tailwind",
    icon: TailwindIcon,
    categories: ["frontend"],
  },
  {
    name: "Sass",
    icon: SassIcon,
    categories: ["frontend"],
  },
  {
    name: "Material UI",
    icon: MaterialUiIcon,
    categories: ["frontend"],
  },
  {
    name: "ShadCN",
    icon: ShadcnIcon,
    categories: ["frontend"],
  },
  {
    name: "Bootstrap",
    icon: BootstrapIcon,
    categories: ["frontend"],
  },
  {
    name: "PayPal",
    icon: PaypalIcon,
    categories: ["backend"],
  },
  {
    name: "Stripe",
    icon: StripeIcon,
    categories: ["backend"],
  },
  {
    name: "Iyzico",
    icon: IyzicoIcon,
    categories: ["backend"],
  },
  {
    name: "Jira",
    icon: JiraIcon,
    categories: ["other"],
  },
  {
    name: "Asana",
    icon: AsanaIcon,
    categories: ["other"],
  },
  {
    name: "Slack",
    icon: SlackIcon,
    categories: ["other"],
  },
];
