import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { Link, Locale, routing } from "@/i18n/routing";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { AlignJustify } from "lucide-react";
import { Button } from "@/components/ui/button";
import ThemeToggle from "@/components/ThemeToggle";
import LanguageSelect from "@/components/LanguageSelect";

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = await params;
  if (!locale || !routing.locales.includes(locale as Locale)) notFound();

  const messages = await getMessages();

  const t = await getTranslations("Menu");

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <NextIntlClientProvider messages={messages}>
            <header className="">
              <nav className="container flex items-center justify-between border-b h-14">
                hey
                <Sheet>
                  <SheetTrigger>
                    <Button variant="outline" asChild className="p-1 size-10">
                      <AlignJustify />
                    </Button>
                  </SheetTrigger>
                  <SheetContent className="flex flex-col spacey-2">
                    <SheetHeader>
                      <SheetTitle>{t("menu")}</SheetTitle>
                    </SheetHeader>
                    <div className="flex-1">
                      <ul className="flex flex-col gap-2">
                        <li>
                          <Link href="/">{t("home")}</Link>
                        </li>
                        <li>
                          <Link href="/about">{t("about")}</Link>
                        </li>
                        <li>
                          <Link href="/projects">{t("projects")}</Link>
                        </li>
                        <li>
                          <Link href="/blogs">{t("blogs")}</Link>
                        </li>
                        <li>
                          <Link href="/contact">{t("contact")}</Link>
                        </li>
                      </ul>
                    </div>
                    <div className="flex gap-2">
                      <ThemeToggle />
                      <LanguageSelect />
                    </div>
                  </SheetContent>
                </Sheet>
              </nav>
            </header>
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
